-- PLEASE DONT BE A LAZY PERSON AND ONLY COPY AND PASTE IT PLS CHANGE THE KICK MESSAGE
-- PLEASE DONT BE A LAZY PERSON AND ONLY COPY AND PASTE IT PLS CHANGE THE KICK MESSAGE

-- PLEASE DONT BE A LAZY PERSON AND ONLY COPY AND PASTE IT PLS CHANGE THE KICK MESSAGE

-- PLEASE DONT BE A LAZY PERSON AND ONLY COPY AND PASTE IT PLS CHANGE THE KICK MESSAGE

-- PLEASE DONT BE A LAZY PERSON AND ONLY COPY AND PASTE IT PLS CHANGE THE KICK MESSAGE

-- PLEASE DONT BE A LAZY PERSON AND ONLY COPY AND PASTE IT PLS CHANGE THE KICK MESSAGE

-- PLEASE DONT BE A LAZY PERSON AND ONLY COPY AND PASTE IT PLS CHANGE THE KICK MESSAGE

-- PLEASE DONT BE A LAZY PERSON AND ONLY COPY AND PASTE IT PLS CHANGE THE KICK MESSAGE

spawn(function()
	local o = {}
	for i,v in pairs(getfenv()) do
		o[v] = true
	end
	while true do
		for i, v in pairs(getfenv()) do
			if tostring(i) == "getgenv" then
          game.Players.LocalPlayer:Kick("Kick message")
      end
		end
		wait()
	end
end)
